title: FYP Showcase (New Colour Theme) # This is a fallback title
description: Animasi FYP Showcase - Retro Edition 2025!
site_brand_name: "Retro-Mation" # For dynamic tab titles

# --- GitHub Pages Configuration ---
# IMPORTANT: Adjust these based on your repository type and name
#
# Option 1: Project Site (e.g., YourUsername.github.io/repository-name)
#   - Your repository name is 'retro-mation'
#   - Your username is 'Ahmad-Amsyar'
baseurl: "/retro-mation" # Must start with a slash and match your repository name
url: "https://Ahmad-Amsyar.github.io" # Your main GitHub Pages domain

# Option 2: User/Organization Site (e.g., YourUsername.github.io)
#   - If your repository is named EXACTLY 'YourUsername.github.io'
# baseurl: ""
# url: "https://YourUsername.github.io"
#
# --- End GitHub Pages Configuration ---


# Define the projects collection
collections:
  projects:
    output: true # Creates a page for each item in _projects
    permalink: /projects/:name/ # URL structure: e.g., /projects/student1-neon-runner/

# Variables for homepage scroller
cards_to_duplicate_for_scroller: 5

# Optional: Default front matter for all pages/posts
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  - scope:
      path: ""
      type: "projects" # Target items in the 'projects' collection
    values:
      layout: "project_detail"
      # You could also add default page.title for projects here if needed,
      # e.g. page.title: "{{ page.project_title }}"
      # but it's already set in the project .md files.

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .jekyll-cache/
  - .jekyll-metadata
  - README.md