title: FYP Showcase (New Colour Theme)
description: Animasi FYP Showcase - Retro Edition 2025!
baseurl: "retro-mation" # If your site is at the root of a domain (e.g., example.com)
url: "https://Ahmad-Amsyar.github.io" # Your site's full URL (e.g., https://username.github.io or http://localhost:4000 for testing)
# If deploying to GitHub Pages at username.github.io/reponame, set:
# baseurl: "/reponame"
# url: "https://username.github.io"

# Define the projects collection
collections:
  projects:
    output: true # Creates a page for each item in _projects
    permalink: /projects/:name/ # URL structure: e.g., /projects/student1-neon-runner/

# Variables for homepage scroller
cards_to_duplicate_for_scroller: 5

# Optional: Default front matter for all pages/posts
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  - scope:
      path: ""
      type: "projects" # Target items in the 'projects' collection
    values:
      layout: "project_detail"

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .jekyll-cache/
  - .jekyll-metadata
  - README.md